export const JOB_SOURCE_PROVIDER = {
  TELEGRAM: "TELEGRAM",
  LINKEDIN: "LINKEDIN",
  NAUKRI: "NAUKRI",
  INDEED: "INDEED",
} as const;

export const JOB_SOURCE_TYPE = {
  TELEGRAM_CHANNEL: "TELEGRAM_CHANNEL",
  TELEGRAM_GROUP: "TELEGRAM_GROUP",
  LINKEDIN: "LINKEDIN",
  NAUKRI: "NAUKRI",
  INDEED: "INDEED",
} as const;

export const JOB_SOURCE_STATUS = {
    ACTIVE: "ACTIVE",
    PAUSED: "PAUSED",
    UNAVAILABLE: "UNAVAILABLE",
} as const;