export const JOB_SOURCE_PROVIDER = {
  TELEGRAM: "TELEGRAM",
  LINKEDIN: "LINKEDIN",
  NAUKRI: "NAUKRI",
  INDEED: "INDEED",
} as const;

export const JOB_SOURCE_TYPE = {
  TELEGRAM_CHANNEL: "TELEGRAM_CHANNEL",
  TELEGRAM_GROUP: "TELEGRAM_GROUP",
  LINKEDIN: "LINKEDIN",
  NAUKRI: "NAUKRI",
  INDEED: "INDEED",
} as const;

export const JOB_SOURCE_STATUS = {
    ACTIVE: "ACTIVE",
    PAUSED: "PAUSED",
    UNAVAILABLE: "UNAVAILABLE",
} as const;

export const SKIPPED_JOB_SOURCES_REASON = {
    ALREADY_EXISTS: "ALREADY_EXISTS",
    DUPLICATE_IN_REQUEST: "DUPLICATE_IN_REQUEST"
} as const;